language: node_js
node_js:
      - 6
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
script: cd test && npm install && ./node_modules/.bin/karma start --browsers PhantomJS --single-run
notifications:
  email:
    recipients:
      - Jonathan.Kanarek@kaltura.com
      - jess.portnoy@kaltura.com
    on_success: change
    on_failure: always
