language: node_js
node_js:
      - 6
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
script: 
    - sed -e "s#1931861#$PARTNER_ID#g" -e "s#83c3d4449a3abbe92ca5966f5f010eb4#$ADMIN_SECRET#g" -e "s#https://www.kaltura.com#https://www.kaltura.com#g" test/config.template.js > test/config.js
    - cd test && npm install && ./node_modules/.bin/karma start --browsers PhantomJS --single-run
notifications:
  email:
    recipients:
      - Jonathan.Kanarek@kaltura.com
      - jess.portnoy@kaltura.com
    on_success: change
    on_failure: always
